---
title: "preprocess_data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{preprocess_data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(DAISIEprep)
library(ape)
```

First the phylogenies need to be loaded using the function `read.nexus` from the
R package `ape`.

```{r}
coccyzus_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Coccyzus.tre")
)
columbiformes_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Columbiformes.tre")
)
finches_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Finches.tre")
)
mimus_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Mimus.tre")
)
myiarchus_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Myiarchus.tre")
)
progne_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Progne.tre")
)
pyrocephalus_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Pyrocephalus.tre")
)
setophaga_tree <- ape::read.nexus(
  file = file.path("inst", "extdata", "Setophaga.tre")
)
```

Currently the phylogenies are loaded as S3 phylo objects, however, we want to
convert them into S4 phylobase objects.

```{r convert phylo to phylo4}
coccyzus_tree <- as(coccyzus_tree, "phylo4")
columbiformes_tree <- as(columbiformes_tree, "phylo4")
finches_tree <- as(finches_tree, "phylo4")
mimus_tree <- as(mimus_tree, "phylo4")
myiarchus_tree <- as(myiarchus_tree, "phylo4")
progne_tree <- as(progne_tree, "phylo4")
pyrocephalus_tree <- as(pyrocephalus_tree, "phylo4")
setophaga_tree <- as(setophaga_tree, "phylo4")
```

Now that all of the phylogenies are loaded we can inspect them.

```{r}
phylobase::plot(coccyzus_tree)
```
