test_that("translate_status works on endemic variants", {
  expect_equal(translate_status("Endemic"), "endemic")
})


      "Endemic"
      "endemic"
      "Non_endemic"
      "Non_Endemic"
      "NonEndemic"
      "Nonendemic"
      "nonendemic"
      "non_endemic"


      "Endemic"
      "endemic"
      "Non_endemic"
      "Non_Endemic"
       "NonEndemic"
       "Nonendemic"
       "nonendemic"
       "non_endemic"


    "Non_endemic_MaxAge"
    "Non_Endemic_MaxAge"
    "Non_Endemic_Max_Age"
    "Non_endemic_maxage"
    "Non_Endemic_Maxage"
    "Non_Endemic_maxage"
    "Non_endemic_Maxage"
    "NonEndemic_MaxAge"

    "Endemic"
    "endemic"

    "Endemic&Non_endemic"
    "Endemic&NonEndemic"
    "Endemic&Non_Endemic"

    "Non_endemic"
    "Non_Endemic"
    "NonEndemic"
    "Nonendemic"
    "nonendemic"
    "non_endemic"

    "Endemic_MaxAge"
    "Endemic_maxage"
    "Endemic_Max_Age"
    "EndemicMaxAge"
    "Endemicmaxage"
    "endemicMaxage"
    "Endemic_Maxage"
    "EndemicMaxage"
    "endemic_maxage"
    "endemicmaxage"
    "endemic_Maxage"
    "endemic_MaxAge"
    "endemic_maxAge"

    "Non_endemic_MaxAgeMinAge"
    "Non_Endemic_MaxAgeMinAge"
    "Non_endemic_MaxAge_MinAge"
    "Non_Endemic_MaxAge_MinAge"
    "Non_Endemic_Max_AgeMinAge"
    "Non_endemic_maxage_minage"
    "Non_Endemic_MaxageminAge"
    "Non_Endemic_maxage_minage"
    "Non_endemic_MaxageMinage"
    "NonEndemic_MaxageMinAge"
    "Nonendemic_MaxageMinAge"
    "Nonendemic_Maxage_MinAge"
    "Nonendemic_maxage_minage"
    "Nonendemic_Maxage_minage"
    "Nonendemic_Maxage_Minage"
    "NonEndemic_MaxAge_MinAge"
    "NonEndemic_Maxage_MinAge"
    "NonEndemic_Maxage_Minage"
    "NonEndemic_maxage_minage"
    "NonEndemic_Maxage_minage"
    "Non_Endemic_maxAgeMinAge"
    "NonEndemic_MaxAge_Minage"
    "Non_Endemic_MaxAge_Minage"
    "NonEndemic_maxage_MinAge"

    "Endemic_MaxAgeMinAge"
    "endemic_MaxAgeMinAge"
    "Endemic_MaxAge_MinAge"
    "Endemic_Maxage_Minage"
    "Endemic_Max_Age_Min_Age"
    "endemic_maxage_minage"
    "endemic_Maxage_minage"
    "endemic_Maxage_Minage"
    "Endemic_Maxage_minage"
    "endemic_maxage_Minage"
    "Endemic_MaxageMinage"
    "Endemic_Maxageminage"
    "Endemic_MaxAge_Minage"
    "Endemic_maxageminage"
    "Endemic_maxageMinage"
